resources:
- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-deployment.git
    branch: master
    private_key: ((git-ssh-key))

- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/kubo-ci
    branch: master

- name: kubo-etcd-release
  type: github-release
  source:
    owner: pivotal-cf-experimental
    repository: kubo-etcd

jobs:
- name: bump-etcd-version
  plan:
  - get: git-kubo-deployment
  - get: git-kubo-ci
  - get: kubo-etcd-release
    trigger: true
  - task: update-manifest
    config:
      platform: linux
      inputs:
      - name: git-kubo-deployment
      - name: git-kubo-ci
      - name: kubo-etcd-release
      outputs:
      - name: git-kubo-deployment-with-bumped-etcd
      run:
        path: ./git-kubo-ci/scripts/update-deployment-etcd.sh
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-with-bumped-etcd
      rebase: true
