---
name: turbulence

releases:
- name: turbulence
  url: https://bosh.io/d/github.com/cppforlife/turbulence-release?v=0.10.0
  version: 0.10.0
  sha1: "259344312796e23500b2836a15140f8f09ad99ee"

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: api
  instances: 1
  azs: [z1]
  jobs:
  - name: turbulence_api
    release: turbulence
    provides:
      api: {shared: true}
    properties:
      password: ((turbulence_api_password))
      cert: ((turbulence_api_cert))
      director:
        host: ((director_ip))
        cert:
          ca: ((director_ssl.ca))
        client: ((director_client))
        client_secret: ((director_client_secret))
  vm_type: minimal
  stemcell: default
  networks:
  - name: default

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-20000
  update_watch_time: 5000-20000

variables:
- name: turbulence_api_password
  type: password
- name: turbulence_api_ca
  type: certificate
  options:
    is_ca: true
    common_name: turbulence_api_ca
- name: turbulence_api_cert
  type: certificate
  options:
    ca: turbulence_api_ca
    common_name: "*.api.default.turbulence.bosh"
