platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/deploy-k8s-instance.sh

params:
  DEPLOYMENT_NAME: ci-service
  WITH_PRIVILEGED_CONTAINERS:
  DEPLOYMENT_OPS_FILE: ~

inputs:
  - name: git-kubo-ci
  - name: gcs-kubo-release-tarball
  - name: git-kubo-deployment
  - name: gcs-bosh-creds
  - name: kubo-lock

outputs:
  - name: gcs-kubeconfig
