platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

inputs:
- name: git-kubo-ci
- name: kubo-lock
- name: gcs-bosh-creds

run:
  path: git-kubo-ci/scripts/install-turbulence-api.sh

params:
outputs:
