platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/ci/run-k8s-integration-tests-ci.sh

params:
  KUBERNETES_AUTHENTICATION_POLICY:
  DEPLOYMENT_NAME: ci-service
  TEST_MULTI_AZ:

inputs:
  - name: git-kubo-ci
  - name: git-kubo-deployment
  - name: gcs-bosh-creds
  - name: kubo-lock
