platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/ci/run-k8s-conformance-tests-ci.sh

params:
  DEPLOYMENT_NAME: ci-service
  CONFORMANCE_RESULTS_DIR: ~
  CONFORMANCE_SPEC_URI: https://raw.githubusercontent.com/cncf/k8s-conformance/master/sonobuoy-conformance.yaml

inputs:
  - name: git-kubo-ci
  - name: gcs-bosh-creds
  - name: kubo-lock
  - name: git-kubo-deployment
  - name: kubo-version

outputs:
  - name: conformance-results
