platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/ci/run-k8s-turbulence-tests-ci.sh

params:
  DEPLOYMENT_NAME:

inputs:
  - name: git-kubo-ci
  - name: gcs-bosh-creds
  - name: kubo-lock
  - name: git-kubo-deployment
