- type: replace
  path: /instance_groups/-
  value:
    name: haproxy
    instances: 1
    networks:
    - name: default
    stemcell: trusty
    vm_type: minimal
    azs:
    - z1
    jobs:
      - name: haproxy
        release: haproxy
        properties:
          ha_proxy:
            backend_port: 30433
            backend_servers: [10.85.96.74, 10.85.96.75, 10.85.96.76]

- type: replace
  path: /releases/-
  value:
    name: haproxy
    version: latest
