- type: replace
  path: /azs/name=z2?
  value:
    name: z2
    cloud_properties:
      zone: us-east1-b

- type: replace
  path: /networks/name=default/subnets/0/azs?
  value: [ z1, z2 ]
- type: remove
  path: /networks/name=default/subnets/0/az?

